- README.md
Since the feature (and security and limitations) list follows the
"Features:" (etc.) line without any empty lines between them,
some Markdown-to-HTML converters (correctly) assume that
they are one paragraph, which causes the list not to
be converted to an actual HTML list. By putting an empty line
between the actual lists and their preceding lines,
the lists will be correctly converted.
(Both lists and paragraphs are block elements,
and they should be "marked down" accordingly.
See https://daringfireball.net/projects/markdown/syntax#block .)
> Properly divide list "headers" and lists.

- TODO
- darkhttpd.c
These commits fix a bug with keep-alive requests and substantially improve their throughput.
A client making quick consecutive requests with keep-alive, such as `ab`
with `-k`, can cause the connection to become hung.
This happens because of an optimization in `http_poll` function. When a
connection state becomes `DONE`, `httpd_poll` recycles the connection
and immediately calls `poll_recv_request`. However, it doesn't handle
this resulting in the connection state becoming `DONE` again. If this
occurs, the state stays in `DONE`, and the further calls to `httpd_poll`
ignore the connection.
Fix this by calling `poll_recv_request` in a loop until the state is no
longer `DONE`.
It looks like `TCP_NODELAY` was disabled due to the bug fixed in the
previous commit. Enabling it substantially …
> Fix hung connection from consecutive requests

- darkhttpd.c
When darkhttpd is running with `--timeout 0` (timeout disabled), and any
connection is idle, it will use 100% of the CPU. This happens because
`select` returns immediately when its timeout is zero, causing the main
`httpd_poll` loop to spin.
Fix this by adding a check to `httpd_poll` making `select` always
receive a `NULL` timeout when `timeout_secs` is zero.
> Fix high CPU usage when timeout is disabled

- darkhttpd.c
This allows client side parsers to decide when a link is a directory.
This is needed for example in the rclone http backend.
https://rclone.org/http/
> Add slash to href for directories

- Makefile
- README.md
- darkhttpd.c
This PR introduces 2 commits. The primary is 95d785acc1e4bc5f1b9ff8bda17ffb51b6f7a5f6. 
Old versions of Solaris did not have vasprintf, so darkhttpd defined one
gated behind an ifdef. Oracle Solaris 10 has had vasprintf since 2011.
Oracle Solaris 11 has had it since release. illumos (which also reports
as `__sun`) also has it in all current incarnations. As a result, this
ifdef'd block creates compiler errors due to a second definition of the
function. This commit removes the block.
This commit also adds `-lsendfile` to the Makefile for systems that
report as `SunOS` in `uname` (Solaris and Illumos), which is necessary
to link successfully in current day
This should bring darkhttpd up to date with the current state of illumos and solaris and allow it to build on those systems. 
In the …
> Update illumos support to the modern era

- darkhttpd.c
* Added mimetypes for image formats apng, avif, webp, webm.
* Added mimetype for .json files.
* Added default mimetypes for font/woff and font/woff2.
* Changed .ogg from application/ogg to audio/ogg, which is more common.
* Added audio/flac, audio/wav.
* Added opus, oga, spx to audio/ogg.
Sources:
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
* https://wiki.xiph.org/MIME_Types_and_File_Extensions
> Changes in default mimetypes

- .gitignore
- README.md
- darkhttpd.c
> Support chroot as non-root on FreeBSD 14+

- darkhttpd.c
- devel/run-tests
This could have already been the default behavior on your OS, but now it will be consistently utilized. Prior to this, to support IPv4 and IPv6 you would have to run two servers or set the relevant sysctl.
Also fixes incorrect inet_pton() usage.
Closes: #37
> Listen to IPv4 and IPv6 at the same time when --ipv6 is passed

- darkhttpd.c
This will prevent `../` from showing up when already in wwwroot.
The string comparison is not super great, because path includes a trailing / and wwwroot does not. I don't think this is buggy, but it's not great.
Closes #33
> Don't include wwwroot in directory list when in wwwroot

- darkhttpd.c
Previously requesting a directory that did not exist just gave a 500 status response. Now the error code set by opendir() is used to give the right response. This is how requesting files is done already, so I just copied the code from there.
> Check why the requested directory failed to open and send correct reply

- darkhttpd.c
Do error when user gives NULL as input for wwwroot and fixed incorrect strlen check for wwwroot.
Previously `./darkhttpd /` and `./darkhttpd ''` would set wwwroot to NULL. Which would still serve /, but I think this is how it was supposed to be in the first place.
> Prevent user from setting wwwroot to NULL

- .gitignore
- devel/run-tests
- devel/test.py
> Don't say tests are successful when they are not

- darkhttpd.c
b051b44 broke macOS build with error:
```
darkhttpd.c:1924:34: error: no member named 'st_mtim' in 'struct stat'
```
> error: no member named 'st_mtim' in 'struct stat'

- darkhttpd.c
Adds required `<!DOCTYPE html>` and removes `<tt>`
closes #57
> Bring generated html up to spec

- darkhttpd.c
In the directory listing the trailing '/' for directories is neglected when figuring out maxlen. This leads to missing space if a directory has the longest name.
This hange accounts for the trailing '/'
> Correct maxlen for directories

- darkhttpd.c
Print the initialized port instead of bindport variable. This is important when using `--port 0` for a random port.
I saw this commit https://github.com/emikulic/darkhttpd/commit/bcadc424a4ff240ef1dd09334ec73b47c6784416 and noticed that the code regressed.
>  display actual port again

- darkhttpd.c
No longer includes ".." when sorting the directory entries for the directory listing, but adds it on top of the listing if the requested directory is not wwwroot. Besides fixing the sorting bug, this should make the sorting faster.
This also does not print the mod date for the ".." entry anymore.
Closes #66
> Fix ".." sorting

- darkhttpd.c
Previously directory listing printed ".." when in wwwroot if wwwroot is not set to ".".
So `./darkhttpd /dir` would have printed the "..".
Same solution like in #44
Sorry for the oversight
> Correct path check for ".."

- COPYING
taken directly from darkhttpd.c
quoting the license:
> Permission to use, copy, modify, and distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
but the copyright notice wasn't present before in the file at all
> Add copyright notice to `COPYING`

- darkhttpd.c
This allows to have plain IPv4 addresses in log, even if listening on an IPv6 socket.
> strip the prefix from ipv4-mapped addresses
